// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDatOHWXbBw0DvbPN8WEOrqDE_ciankDOM',
    appId: '1:277215110061:web:191b025759d12e93a73724',
    messagingSenderId: '277215110061',
    projectId: 'workflow-app-68b1e',
    authDomain: 'workflow-app-68b1e.firebaseapp.com',
    storageBucket: 'workflow-app-68b1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDXzEAjFAM96pBsn0QGtG6AoGeofc0m9s',
    appId: '1:277215110061:android:23a475d2416c9e13a73724',
    messagingSenderId: '277215110061',
    projectId: 'workflow-app-68b1e',
    storageBucket: 'workflow-app-68b1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnyljXbeZ5cUOyo-knvERccnWBY2WxQMU',
    appId: '1:277215110061:ios:4a8ce054ba42ef44a73724',
    messagingSenderId: '277215110061',
    projectId: 'workflow-app-68b1e',
    storageBucket: 'workflow-app-68b1e.firebasestorage.app',
    iosBundleId: 'com.example.workflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnyljXbeZ5cUOyo-knvERccnWBY2WxQMU',
    appId: '1:277215110061:ios:4a8ce054ba42ef44a73724',
    messagingSenderId: '277215110061',
    projectId: 'workflow-app-68b1e',
    storageBucket: 'workflow-app-68b1e.firebasestorage.app',
    iosBundleId: 'com.example.workflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDatOHWXbBw0DvbPN8WEOrqDE_ciankDOM',
    appId: '1:277215110061:web:af6eca7d5f7a8b67a73724',
    messagingSenderId: '277215110061',
    projectId: 'workflow-app-68b1e',
    authDomain: 'workflow-app-68b1e.firebaseapp.com',
    storageBucket: 'workflow-app-68b1e.firebasestorage.app',
  );
}
